cmflow/cmflow/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("comments.urls")),
]  # noqa: E501

cmflow/comments/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.base_view, name="spa"),
    path("comment_add", views.comment_add, name="comment_add"),
    path("like_add", views.like_add, name="like_add"),
    path("like_remove", views.like_remove, name="like_remove"),
]

cmflow/comments/models.py
from django.db import models


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=100)
    email = models.EmailField()
    parent_comment = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True
    )
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    home_page_url = models.URLField(blank=True, null=True)


class Attachment(models.Model):
    attachment_id = models.AutoField(primary_key=True)
    comment = models.ForeignKey(
        Comment, related_name="attachments", on_delete=models.CASCADE
    )
    file_path = models.FileField(upload_to="attachments/")
    file_type = models.CharField(max_length=50)


class Like(models.Model):
    like_id = models.AutoField(primary_key=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.CharField(max_length=100, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

cmflow/comments/views.py
import os

import jwt
import requests
from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from .misc import check_image_format  # noqa: F401
from .misc import check_file, check_image_size, scale_image, upload_to_bucket
from .models import Attachment, Comment, Like  # noqa: F401


def base_view(request):
    sort = request.GET.get("sort", "date_added")
    direction = request.GET.get("direction", "desc")
    valid_sort_fields = ["user_name", "email", "date_added"]
    sort = "date_added" if sort not in valid_sort_fields else sort
    order_by_field = sort if direction == "asc" else f"-{sort}"
    comments_list = Comment.objects.prefetch_related("attachments").order_by(
        order_by_field
    )  # noqa: E501
    paginator = Paginator(comments_list, 25)

    page_number = request.GET.get("page")
    comments = paginator.get_page(page_number)
    context = {
        "comments": comments,
        "jwt_token": request.session.get("jwt_token", ""),
    }  # noqa: E501
    return render(request, "index.html", context)


@require_http_methods(["POST"])
def comment_add(request):
    recaptcha_response = request.POST.get("g-recaptcha-response")
    data = {
        "secret": os.getenv("RECAPTCHA_SECRET_KEY"),
        "response": recaptcha_response,
    }
    result = requests.post(
        "https://www.google.com/recaptcha/api/siteverify", data=data
    )  # noqa: E501
    result_json = result.json()

    if not result_json.get("success"):
        return JsonResponse({"error": "Invalid CAPTCHA"}, status=400)

    # Retrieve the JWT token from the session
    token = request.session.get("jwt_token")
    if not token:
        return HttpResponseForbidden("Authentication required")

    try:
        # Decode the token to get user information
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
        user_id = payload.get("user_id")
        if not user_id:
            return HttpResponseForbidden("Invalid token")

        # Retrieve and process the comment data
        user_name = request.POST.get("user_name")
        email = request.POST.get("email")
        text = request.POST.get("text")
        photo = (  # noqa: F841
            request.FILES.get("photo") if "photo" in request.FILES else None
        )
        file = (  # noqa: F841
            request.FILES.get("file") if "file" in request.FILES else None
        )
        home_page_url = request.POST.get("home_page_url")
        parent_comment_id = request.POST.get("reply_id")

        parent_comment = None
        if parent_comment_id:
            try:
                parent_comment = Comment.objects.get(
                    comment_id=parent_comment_id
                )  # noqa: E501
            except Comment.DoesNotExist:
                return JsonResponse(
                    {"message": "Parent comment not found"}, status=404
                )  # noqa: E501

        # Create and save the comment
        comment = Comment(
            user_name=user_name,
            email=email,
            text=text,
            home_page_url=home_page_url,
            parent_comment=parent_comment,
        )
        comment.save()
        if photo:
            if not check_image_format(
                photo,
                [
                    "JPG",
                    "JPEG",
                    "GIF",
                    "PNG",
                    "jpg",
                    "jpeg",
                    "gif",
                    "png",
                ],  # noqa: E501
            ):
                return JsonResponse(
                    {"error": "Invalid image format"}, status=405
                )  # noqa: E501

            if not check_image_size(photo, 320, 240):
                photo = scale_image(photo, 320, 240)
            # Upload the processed photo
            photo_url = upload_to_bucket(photo.name, photo, photo.content_type)
            attachment = Attachment(
                comment=comment,
                file_path=photo_url,
                file_type=photo.content_type,
            )
            attachment.save()
        if file:
            if not check_file(file):
                return JsonResponse(
                    {"error": "Invalid file size or format"}, status=405
                )

            # Upload the file
            file_url = upload_to_bucket(file.name, file, file.content_type)
            attachment = Attachment(
                comment=comment,
                file_path=file_url,
                file_type=file.content_type,
            )
            attachment.save()

        try:
            response_data = {
                "message": "Comment added successfully",
                "comment": {
                    "id": comment.comment_id,
                    "user_name": comment.user_name,
                    "text": comment.text,
                    "home_page_url": comment.home_page_url,
                    # Add other relevant fields
                },
            }
            return JsonResponse(response_data)

        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

    except jwt.ExpiredSignatureError:
        return HttpResponseForbidden("Token has expired")

    except jwt.InvalidTokenError:
        return HttpResponseForbidden("Invalid token")


@require_http_methods(["POST"])
def like_add(request):
    comment_id = request.POST.get("comment_id")
    user_id = request.session.get(
        "user_id", request.user.id
    )  # Use session user_id for anonymous users

    # Ensure the comment exists
    try:
        comment = Comment.objects.get(pk=comment_id)
    except Comment.DoesNotExist:
        return JsonResponse({"error": "Comment not found"}, status=404)

    # Check if the like already exists
    if not Like.objects.filter(comment=comment, user=user_id).exists():
        Like.objects.create(comment=comment, user=user_id)
        updated_like_count = get_new_like_count(comment_id)

        return JsonResponse({"new_like_count": updated_like_count})
    else:
        return JsonResponse({"error": "Like already exists"}, status=400)


@require_http_methods(["POST"])
def like_remove(request):
    comment_id = request.POST.get("comment_id")
    user_id = request.session.get(
        "user_id", request.user.id
    )  # Use session user_id for anonymous users

    # Ensure the comment exists
    try:
        comment = Comment.objects.get(pk=comment_id)
    except Comment.DoesNotExist:
        return JsonResponse({"error": "Comment not found"}, status=404)

    # Check if the like exists and delete it
    like = Like.objects.filter(comment=comment, user=user_id).first()
    if like:
        like.delete()
        updated_like_count = get_new_like_count(comment_id)

        return JsonResponse({"new_like_count": updated_like_count})
    else:
        return JsonResponse({"error": "Like not found"}, status=404)


def get_new_like_count(comment_id):
    """Retrieve the updated like count for a specific comment."""
    try:
        comment = Comment.objects.get(comment_id=comment_id)
    except Comment.DoesNotExist:
        return 0  # or handle the error as appropriate

    # Assuming your Like model has a foreign key to Comment
    like_count = Like.objects.filter(comment=comment).count()
    return like_count

cmflow/comments/templates/comment.html
{% load custom_filters %}
<div class="col">
    <div class="d-flex flex-start">
        <img class="rounded-circle shadow-1-strong me-3" src="https://cdn.iconscout.com/icon/free/png-256/free-avatar-370-456322.png" alt="avatar" width="65" height="65" />
        <div class="flex-grow-1 flex-shrink-1">
            <div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="mb-1">
                        {{ comment.user_name }} <span class="small">- {{ comment.date_added }}</span>
                        {% if comment.home_page_url %}
                            <a href="{{ comment.home_page_url }}"><svg xmlns="http://www.w3.org/2000/svg" height="16" width="18" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z"/></svg></a>
                        {% endif %}
                        {% if not forloop.parentloop %}
                            <span id="like-count-{{ comment.comment_id }}">{{ comment.like_set.count }}</span>
                        {% else %}
                            <span id="like-count-{{ comment.comment_id }}">{{ child_like_count }}</span>
                        {% endif %}
                        <div id="like-button-{{ comment.comment_id }}" style="cursor:pointer; display: {% if not comment|user_has_liked:request.session.user_id and not child_is_liked %}block{% else %}none{% endif %};">
                            <div onclick="likePost({{ comment.comment_id }});">
                                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512">
                                    <path d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z"/>
                                </svg>
                            </div>
                        </div>
                        <!-- Unlike button -->
                        <div id="unlike-button-{{ comment.comment_id }}" style="cursor:pointer; display: {% if comment|user_has_liked:request.session.user_id or child_is_liked %}block{% else %}none{% endif %};">
                            <div onclick="unlikePost({{ comment.comment_id }});">
                                <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512">
                                    <path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/>
                                </svg>
                            </div>
                        </div>
                    </p>
                    <a href="#!" class="replyLink" data-reply-id="{{ comment.comment_id }}"><i style="color: black;" class="fas fa-reply fa-xs"></i><span class="small"></span></a>
                </div>
                <p class="small mb-0">
                    {{ comment.text |escape_html|safe}}
                </p>
                <div class="attachments">
                    {% for attachment in comment.attachments.all %}
                        {% if attachment.file_type|startswith:"image"  %}
                            <a href="{{ attachment.file_path }}" target="_blank"><img src="{{ attachment.file_path }}" alt="attachment" width="340" height="340"></a>
                        {% else %}
                            <a href="{{ attachment.file_path }}" target="_blank">{{ attachment.file_path }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <!-- Render child comments -->
            {% for child in comment.comment_set.all %}
                {% with child_like_count=child.like_set.count %}
                    {% if child|user_has_liked:request.session.user_id %}
                        {% include 'comment.html' with comment=child like_count=child_like_count child_is_liked=True %}
                    {% else %}
                        {% include 'comment.html' with comment=child like_count=child_like_count child_is_liked=False %}
                    {% endif %}
                {% endwith %}
            {% endfor %}
        </div>
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var parentElement = document.body; // Adjust this to the closest common ancestor of your .replyLink elements
    var replyIdInput = document.getElementById('replyId');
    var replyMessage = document.getElementById('replyMessage'); // Get the h3 element

    parentElement.addEventListener('click', function(event) {
        var target = event.target;

        // Traverse up the DOM to find the .replyLink ancestor, if it exists
        while (target && target !== parentElement) {
            if (target.matches('.replyLink')) {
                var replyId = target.getAttribute('data-reply-id');
                replyIdInput.value = replyId; // Set the reply ID in the input field

                // Update the h3 element with a message
                replyMessage.textContent = 'You are replying to comment ID: ' + replyId;

                return; // Stop the loop after setting the value and updating the message
            }
            target = target.parentElement;
        }
    });
});

document.addEventListener('DOMContentLoaded', function() {
    var parentElement = document.body; // Adjust this to the closest common ancestor of your .replyLink elements
    var replyIdInput = document.getElementById('replyId');

    parentElement.addEventListener('click', function(event) {
        var target = event.target;

        // Traverse up the DOM to find the .replyLink ancestor, if it exists
        while (target && target !== parentElement) {
            if (target.matches('.replyLink')) {
                var replyId = target.getAttribute('data-reply-id');
                replyIdInput.value = replyId; // Set the reply ID in the input field
                return; // Stop the loop after setting the value
            }
            target = target.parentElement;
        }
    });
});

</script>
<script>
function updateLikeCount(commentId, newLikeCount) {
    console.log("Updating like count for comment", commentId, "to", newLikeCount); // Debugging

    const likeCountElement = document.getElementById('like-count-' + commentId);
    console.log("Found like count element:", likeCountElement); // Debugging

    if (likeCountElement) {
        likeCountElement.innerText = newLikeCount;
    } else {
        console.error("Failed to find like count element for commentId:", commentId);
    }
}

function likePost(commentId) {
    fetch('/like_add', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'X-CSRFToken': getCSRFToken()
        },
        body: 'comment_id=' + commentId
    })
    .then(response => response.json())
    .then(data => {
        updateLikeCount(commentId, data.new_like_count);
    })
    .catch(error => console.error('Error:', error));

    const likeButton = document.getElementById('like-button-' + commentId);
    const unlikeButton = document.getElementById('unlike-button-' + commentId);

    likeButton.style.display = 'none';
    unlikeButton.style.display = 'block';
}


function getCSRFToken() {
    return document.querySelector('[name=csrfmiddlewaretoken]').value;
}

function unlikePost(commentId) {
    fetch('/like_remove', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'X-CSRFToken': getCSRFToken()
        },
        body: 'comment_id=' + commentId
    })
    .then(response => response.json())
    .then(data => {
        updateLikeCount(commentId, data.new_like_count);
    })
    .catch(error => console.error('Error:', error));

    const likeButton = document.getElementById('like-button-' + commentId);
    const unlikeButton = document.getElementById('unlike-button-' + commentId);

    likeButton.style.display = 'block';
    unlikeButton.style.display = 'none';

}
</script>

cmflow/comments/templates/form.html
<div class="container">
    <div id="preview" class="preview mt-5"></div>
    <h2 class="mt-5">Post a Comment</h2>
    <p id="replyMessage"></p>
    <form id="commentForm" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" id="jwtToken" value="{{ jwt_token }}">
        <div class="mb-3">
            <label for="userName" class="form-label">User Name</label>
            <input type="text" class="form-control" id="userName" name="user_name" pattern="[A-Za-z0-9]+" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">E-mail</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="mb-3">
            <div class="toolbar">
                <button class="btn btn-primary" onclick="wrapTag('i')">[i]</button>
                <button class="btn btn-primary" onclick="wrapTag('strong')">[strong]</button>
                <button class="btn btn-primary" onclick="wrapTag('code')">[code]</button>
                <button class="btn btn-primary" onclick="wrapTag('a')">[a]</button>
            </div>
            <label for="text" class="form-label">Comment</label>
            <textarea class="form-control" id="text" name="text" rows="3" required oninput="updatePreview()"></textarea>
        </div>

        <div class="mb-3">
            <label for="homePageUrl" class="form-label">Home Page URL</label>
            <input type="url" class="form-control" id="homePageUrl" name="home_page_url">
        </div>
        <div class="mb-3">
            <label for="photo" class="form-label">Attach Photo</label>
            <input class="form-control" type="file" id="photo" name="photo" accept="image/*">
        </div>
        <div class="mb-3">
            <label for="file" class="form-label">Attach File</label>
            <input class="form-control" type="file" id="file" name="file">
        </div>
        <!-- Hidden field for reply ID -->
        <input type="hidden" id="replyId" name="reply_id" value="">
        <div class="g-recaptcha" data-sitekey="6Ld1uEwpAAAAAI_TGl4DY__m1ZpcPcQNZ5KJOfhy"></div>
        <!-- Replace REPLY_ID_VALUE with the actual reply ID or the variable containing it -->
        <button type="submit" class="btn btn-primary submitform">Submit</button>
    </form>
</div>
<script>
    function wrapTag(tag) {
        var textArea = document.getElementById('text');
        var selectedText = textArea.value.substring(textArea.selectionStart, textArea.selectionEnd);
        var beforeText = textArea.value.substring(0, textArea.selectionStart);
        var afterText = textArea.value.substring(textArea.selectionEnd);

        if (tag === 'a') {
            var url = prompt('Enter the URL:', 'http://');
            textArea.value = beforeText + '<a href="' + url + '">' + selectedText + '</a>' + afterText;
        } else {
            textArea.value = beforeText + '<' + tag + '>' + selectedText + '</' + tag + '>' + afterText;
        }
    }
</script>
<script>
function escapeHTML(text) {
    var map = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#039;'
    };

    return text.replace(/[&<>"']/g, function(m) { return map[m]; });
}

function updatePreview() {
    var inputText = document.getElementById('text').value;
    document.getElementById('preview').innerHTML = inputText;
}
</script>
<script>
function postComment(event) {
    event.preventDefault();  // Prevent the default form submission

    var formData = new FormData(document.getElementById('commentForm'));
    var textElement = document.getElementById('text');
    if (textElement) {
        var escapedText = escapeHTML(textElement.value);
        formData.set('text', escapedText); // Update the 'text' field in the FormData
    }
    const jwtToken = document.getElementById('jwtToken').value;  // Retrieve the JWT token

    fetch('/comment_add', {
        method: 'POST',
        body: formData,  // Send the form data
        headers: {
            'Authorization': `Bearer ${jwtToken}`  // Include the JWT token in the Authorization header
        },
        credentials: 'include'  // Necessary for cookies (including CSRF token) to be sent
    })
    .then(response => response.json())
    .then(data => {
        if (data.error) {
            throw new Error(data.error);
        }
        console.log(data.message);
        document.getElementById('commentForm').reset();
        window.location.reload();
    })
    .catch(error => {
        console.error('Error:', error);
    });
}

// Add event listener to the form
document.getElementById('commentForm').addEventListener('submit', postComment);

</script>

cmflow/comments/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
    <link href="../static/main.css" rel="stylesheet">

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-3">
                {% include 'form.html' %}
            </div>
            <div class="col-lg-9">
                <div class="sorting-buttons mb-3 mt-3">
                    <!-- Sort by User Name -->
                    <a href="?sort=user_name&direction=asc" class="btn btn-primary"><i class="fas fa-sort-alpha-up"></i> <i class="fas fa-user"></i></a>
                    <a href="?sort=user_name&direction=desc" class="btn btn-primary"><i class="fas fa-sort-alpha-down"></i> <i class="fas fa-user"></i></a>

                    <!-- Sort by E-mail -->
                    <a href="?sort=email&direction=asc" class="btn btn-primary"><i class="fas fa-sort-alpha-up"></i> <i class="fas fa-envelope"></i></a>
                    <a href="?sort=email&direction=desc" class="btn btn-primary"><i class="fas fa-sort-alpha-down"></i> <i class="fas fa-envelope"></i></a>

                    <!-- Sort by Date Added -->
                    <a href="?sort=date_added&direction=asc" class="btn btn-primary"><i class="fas fa-sort-numeric-up"></i> <i class="fas fa-calendar"></i></a>
                    <a href="?sort=date_added&direction=desc" class="btn btn-primary"><i class="fas fa-sort-numeric-down"></i> <i class="fas fa-calendar"></i></a>
                </div>
                <div class="card">
                    <div class="card-body p-4">
                        <h4 class="text-center mb-4 pb-2">Comments section</h4>
                        <div class="row">
                            <div class="col">
                                {% for comment in comments %}
                                    {% if not comment.parent_comment %}
                                        {% include 'comment.html' with comment=comment %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pagination justify-content-center">
                    <span class="step-links">
                        {% if comments.has_previous %}
                            <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                            <a class="btn btn-primary" href="?page={{ comments.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
                        </span>

                        {% if comments.has_next %}
                            <a class="btn btn-primary" href="?page={{ comments.next_page_number }}">next</a>
                            <a class="btn btn-primary" href="?page={{ comments.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
</body>
</html>